/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.14
 * Generated at: 2016-04-13 22:01:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\"> \r\n");
      out.write("<title>Login_Empleado</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t/*.body{\r\n");
      out.write("  height: 150px;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("\t}*/\r\n");
      out.write("\t#FonLogin{\r\n");
      out.write("\t \twidth: 400px;\r\n");
      out.write("\t \theight:200px;\r\n");
      out.write("\t \tmargin:0 auto;\r\n");
      out.write("\t \tmargin-top:50px;\r\n");
      out.write("\t \tbackground-color: white;\r\n");
      out.write("\t \ttext-align: center;\r\n");
      out.write("\t \tborder-radius: 29px 29px 29px 29px;\r\n");
      out.write("\t\t-moz-border-radius: 29px 29px 29px 29px;\r\n");
      out.write("\t\t-webkit-border-radius: 29px 29px 29px 29px;\r\n");
      out.write("\t\tborder: 0px solid #000000;\r\n");
      out.write("\t\t-webkit-box-shadow: 2px 10px 35px 3px rgba(0,0,0,0.75);\r\n");
      out.write("\t\t-moz-box-shadow: 2px 10px 35px 3px rgba(0,0,0,0.75);\r\n");
      out.write("\t\tbox-shadow: 2px 10px 35px 3px rgba(0,0,0,0.75);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#margint{\r\n");
      out.write("\t\tpadding-left: 10px;\r\n");
      out.write("\t\tpadding-right: 10px;\r\n");
      out.write("\t\tpadding-top: 20px;\t\r\n");
      out.write("\t}\r\n");
      out.write("\t#spaceimage{\r\n");
      out.write("\t\tpadding-left: 20px;\r\n");
      out.write("\t\tpadding-right: 20px;\r\n");
      out.write("\t\tpadding-top: 20px;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#A4C7C9\">\r\n");
      out.write("<div id=\"FonLogin\" align=\"center\" border=2>\r\n");
      out.write("\t<form action=\"ServletValidacion\" method=\"post\" >\r\n");
      out.write("\t\t<table >\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td id=\"spaceimage\">\r\n");
      out.write("\t\t\t\t<img width=\"150px\" height=\"150px\" src=\"img/login.png\"/>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td id=\"margint\">\r\n");
      out.write("\t\t\t<input width=\"100px\" type=\"text\" name=\"email\" placeholder=\"Usuario\"\t/><br/><br/>\r\n");
      out.write("\t\t\t<input type=\"password\" name=\"pass\" \tplaceholder=\"Contraseña\" ><br/><br/>\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Iniciar Sesión\">\r\n");
      out.write("\t\t\t<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\t\t\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\t\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
